apiVersion: apps/v1
kind: Deployment
metadata:
   name: pod-replicasetmatchexp
spec:
   replicas: 3
   selector:
     matchExpressions:
     - key: app
       operator: In
       values: 
         - web
   template:
     metadata:
       labels:
         app: web
     spec:
      containers:
      - name: mysql
        image: santyrocker/demo-image:8080
