apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argoc-demo
spec:
  selector:
    matchLabels:
     app: web
  replicas: 3
  serviceName: nodeport-pod
  template:
    metadata:
     labels:
       app: web
    spec:
     containers:
     - name: website
       image: santyrocker/demo-image:8080
