apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
     app: web
  replicas: 3
  serviceName: clusterip
  template:
    metadata:
     labels:
       app: web
    spec:
     containers:
     - name: website
       image: nginx
