apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sam
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  volumeClaimTemplates:
  - apiVersion: v1	
    kind: PersistentVolumeClaim
    metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-nfs-storage
      resources:
        requests:
          storage: 1Gi
  selector:
    matchLabels:
     app: web
  replicas: 3
  serviceName: nodeport-pod
  updateStrategy:
    type: OnDelete
  template:
    metadata:
     labels:
       app: web
    spec:
     containers:
     - name: website
       image: santyrocker/demo-image:8080
       volumeMounts:
       - mountPath: /root/satya
         name: www 
